version: '3'
services:
  database:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=Shop
    volumes:
      - ../src/create_db.sh:/docker-entrypoint-initdb.d/create_db.sh
      - ../src/create_script.sql:/docker-entrypoint-initdb.d/create_script.sql
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080